---
- name: Configure Nexus switches with Jinja templates
  hosts: leaf_switches
  gather_facts: false

  tasks:

    # - name: Configure SNMP
    #   cisco.nxos.nxos_config:

    - name: for idempotency, use full-form commands
      cisco.nxos.nxos_config:
        lines:
          # - shutdown
        - no shut
        # parents: int eth1/1
        parents: interface Ethernet1/1
    
    - name: Merge provided configuration with device configuration
      cisco.nxos.nxos_interfaces:
        config:
        - name: Ethernet1/1
          description: Configured by Ansible
          enabled: true
        state: merged
...



###

conf terminal
interface Ethernet1/1
  shutdown
!
